export { default as authRoutes } from "./auth.routes.js"
export { default as userRoutes } from "./user.routes.js"
export { default as postRoutes } from "./post.routes.js"
export { default as followsRoutes } from "./follow.routes.js"
export { default as likesRoutes } from "./like.routes.js"
export { default as commentsRoutes } from "./comment.routes.js"
export { default as messagesRoutes } from "./messages.routes.js"